# A moderately useful Makefile

# SRC is set to all the .cpp files in the current directory

SRC = $(wildcard *.cpp)

# The OBJ macro is built from the SRC macro

OBJ = $(SRC:.cpp=.o)

# Macros for the compiler, linker, and compiler options

GCC = g++
LINK = g++

CFLAGS = -Wall -std=c++11 -c
CXXFLAGS = $(CFLAGS)

all: main
 
# The 'main' target depends on the files in the OBJ macro
# $^ is a make macro that contains the target dependencies
# $@ is a make macro that contains the target

main: $(OBJ)
	g++ -o $@ $^ $(CXXFLAGS)

# Add a clean target to allow rebuilds

clean:
	rm -rf main *.o
